"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# 프로덕션 환경에서는 반드시 DEBUG=False로 설정
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# 개발 환경: 기본값 사용 가능
# 프로덕션 환경: 환경변수 필수 (없으면 시작 실패)
if DEBUG:
    SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-only-do-not-use-in-production')
else:
    SECRET_KEY = os.getenv('SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError("SECRET_KEY environment variable is required in production")

# ALLOWED_HOSTS 설정
# 프로덕션: 실제 도메인만 허용
# 개발: ['*'] 또는 ['localhost', '127.0.0.1']
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'corsheaders',  # CORS 설정
    'ninja',
    # Local apps
    'core',  # CoreModel 제공
    'users',
    'campaigns',
    'app_config',  # 앱 설정 관리
    'keyword_alerts',  # 키워드 알람
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise - static 파일 서빙
    'corsheaders.middleware.CorsMiddleware',  # CORS - 최상단 가까이 위치
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 테스트 환경: SQLite 사용 (빠르고 간편)
# 개발/프로덕션: PostgreSQL 사용
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'test'),
            'USER': os.getenv('POSTGRES_USER', 'test'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'test1234'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'DISABLE_SERVER_SIDE_CURSORS': True,  # PostgreSQL 13 compatibility
        }
    }

# PostgreSQL 13 임시 호환성 (추후 PostgreSQL 14+로 업그레이드 필요)
# Django 5.2는 PostgreSQL 14+를 요구하지만, 현재 13.21 사용 중
from django.db.backends.postgresql.features import DatabaseFeatures
DatabaseFeatures.minimum_database_version = (13, 0)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = []

# WhiteNoise configuration for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# JWT 인증 설정
# 개발 환경: SECRET_KEY를 기본값으로 사용
# 프로덕션 환경: 환경변수 필수 (없으면 시작 실패)
if DEBUG:
    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
else:
    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
    if not JWT_SECRET_KEY:
        raise ValueError("JWT_SECRET_KEY environment variable is required in production")

JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', '60'))
JWT_REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv('JWT_REFRESH_TOKEN_EXPIRE_DAYS', '7'))

# Apple Sign In 설정
APPLE_CLIENT_ID = os.getenv('APPLE_CLIENT_ID', 'com.reviewmaps.app')

# 익명 사용자 세션 설정
ANONYMOUS_SESSION_EXPIRE_HOURS = int(os.getenv('ANONYMOUS_SESSION_EXPIRE_HOURS', '60'))

# CORS (Cross-Origin Resource Sharing) 설정
# Mobile app (Android/iOS)에서 API 호출을 위한 설정
# Mobile app은 Origin 헤더가 없거나 null이므로 모든 origin 허용
CORS_ALLOW_ALL_ORIGINS = True  # Mobile app 지원

# 또는 특정 도메인만 허용하려면 아래 사용 (웹 클라이언트 추가 시)
# CORS_ALLOWED_ORIGINS = [
#     "https://review-maps.com",
#     "https://www.review-maps.com",
# ]

# CORS 허용 메서드
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS 허용 헤더
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Credentials 허용 (쿠키, 인증 헤더 등)
CORS_ALLOW_CREDENTIALS = True

# CSRF (Cross-Site Request Forgery) 설정
# CSRF 검증을 통과할 신뢰할 수 있는 origin 목록
# 프로덕션 도메인을 여기에 추가
CSRF_TRUSTED_ORIGINS = [
    'https://api.review-maps.com',
    'https://review-maps.com',
    'https://www.review-maps.com',
]

# 개발 환경에서 localhost 추가
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])

# ===== 보안 설정 검증 (프로덕션 환경) =====
import logging

if not DEBUG:
    # ALLOWED_HOSTS 검증
    if ALLOWED_HOSTS == ['*']:
        logging.warning("⚠️ SECURITY WARNING: ALLOWED_HOSTS is set to ['*'] in production!")
        logging.warning("⚠️ Please set specific domain names in ALLOWED_HOSTS.")
else:
    # 개발 환경에서는 경고만 출력
    logging.basicConfig(level=logging.INFO)
    logging.info("🔧 Development mode enabled (DEBUG=True)")
