# Generated by Django 5.2.8 on 2025-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', '이메일'), ('google', 'Google'), ('apple', 'Apple'), ('kakao', 'Kakao'), ('naver', 'Naver')], default='email', help_text='사용자가 가입한 방식 (email, google, apple, kakao, naver)', max_length=20, verbose_name='로그인 방식'),
        ),
    ]
