# Generated by Django 5.2.8 on 2025-11-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', 'Kakao'), ('google', 'Google'), ('apple', 'Apple')], max_length=20, verbose_name='SNS 제공자')),
                ('provider_user_id', models.CharField(help_text='Kakao ID, Google ID, Apple ID 등', max_length=255, verbose_name='SNS 제공자의 사용자 ID')),
                ('email', models.EmailField(help_text='SNS 제공자로부터 받은 이메일', max_length=254, verbose_name='SNS 이메일')),
                ('name', models.CharField(blank=True, help_text='SNS 제공자로부터 받은 이름', max_length=100, verbose_name='이름')),
                ('profile_image', models.URLField(blank=True, verbose_name='프로필 이미지 URL')),
                ('access_token', models.TextField(blank=True, help_text='암호화 필요 (향후 구현)', verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, help_text='암호화 필요 (향후 구현)', verbose_name='리프레시 토큰')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'SNS 계정',
                'verbose_name_plural': 'SNS 계정',
                'db_table': 'social_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_user_id'], name='idx_provider_user'), models.Index(fields=['user', 'provider'], name='idx_user_provider')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
