# Generated by Django 5.2.8 on 2025-11-19 16:17

from django.db import migrations, models


def populate_username(apps, schema_editor):
    """기존 사용자의 username을 email + login_method 조합으로 채우기"""
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.username = f"{user.email}_{user.login_method}"
        user.save()


def reverse_populate_username(apps, schema_editor):
    """롤백 시 username을 빈 문자열로 되돌리기"""
    User = apps.get_model('users', 'User')
    User.objects.all().update(username='')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', editable=False, help_text='email + login_method 조합으로 자동 생성', max_length=255, unique=True, verbose_name='사용자명'),
        ),
        migrations.RunPython(populate_username, reverse_populate_username),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='사용자 로그인용 이메일 주소', max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'login_method')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'login_method'], name='idx_email_login_method'),
        ),
    ]
