# Generated by Django 5.2.8 on 2025-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', help_text='SNS 로그인 시 제공받은 사용자 이름', max_length=100, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='', help_text='SNS 로그인 시 제공받은 프로필 이미지 URL', max_length=500, verbose_name='프로필 이미지 URL'),
        ),
    ]
