# Generated by Django 5.2.8 on 2025-11-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.CharField(max_length=6, verbose_name='인증코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('attempts', models.IntegerField(default=0, verbose_name='시도 횟수')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료 여부')),
                ('verification_token', models.CharField(blank=True, help_text='인증 완료 후 발급되는 토큰 (회원가입 시 사용)', max_length=255, verbose_name='인증 토큰')),
                ('send_count', models.IntegerField(default=1, verbose_name='발송 횟수')),
                ('last_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='마지막 발송 시간')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='idx_email_code'), models.Index(fields=['email', 'is_verified'], name='idx_email_verified')],
            },
        ),
    ]
