# Generated by Django 5.2.8 on 2025-11-14 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('display_order', models.IntegerField(default=99, verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'db_table': 'categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(unique=True, verbose_name='원본 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '원본 카테고리',
                'verbose_name_plural': '원본 카테고리',
                'db_table': 'raw_categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.category', verbose_name='표준 카테고리')),
                ('raw_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.rawcategory', verbose_name='원본 카테고리')),
            ],
            options={
                'verbose_name': '카테고리 매핑',
                'verbose_name_plural': '카테고리 매핑',
                'db_table': 'category_mappings',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, verbose_name='플랫폼')),
                ('company', models.CharField(max_length=255, verbose_name='업체명')),
                ('company_link', models.TextField(blank=True, null=True, verbose_name='업체 링크')),
                ('offer', models.TextField(verbose_name='제공 내용')),
                ('apply_deadline', models.DateTimeField(blank=True, null=True, verbose_name='신청 마감일')),
                ('review_deadline', models.DateTimeField(blank=True, null=True, verbose_name='리뷰 마감일')),
                ('apply_from', models.DateTimeField(blank=True, null=True, verbose_name='신청 시작일')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='이미지 URL')),
                ('content_link', models.TextField(blank=True, null=True, verbose_name='콘텐츠 링크')),
                ('search_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='검색 텍스트')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='출처')),
                ('title', models.TextField(blank=True, null=True, verbose_name='제목')),
                ('campaign_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='캠페인 유형')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='지역')),
                ('campaign_channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='캠페인 채널')),
                ('promotion_level', models.IntegerField(default=0, verbose_name='프로모션 레벨')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '캠페인',
                'verbose_name_plural': '캠페인',
                'db_table': 'campaign',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['promotion_level', 'apply_deadline', 'lat', 'lng'], name='idx_cpg_promo_ddl_loc'), models.Index(fields=['created_at'], name='idx_cpg_created'), models.Index(fields=['category'], name='idx_cpg_category'), models.Index(fields=['apply_deadline'], name='idx_cpg_deadline')],
            },
        ),
    ]
