# Generated by Django 5.2.8 on 2025-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='idx_cpg_created',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='idx_cpg_created'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['region'], name='idx_cpg_region'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='idx_cpg_type'),
        ),
    ]
