# Generated by Django 5.2.8 on 2025-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='플랫폼')),
                ('ad_network', models.CharField(help_text='예: admob, applovin, unity, etc.', max_length=50, verbose_name='광고 네트워크')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('ad_unit_ids', models.JSONField(default=dict, help_text='banner_id, interstitial_id, native_id, rewarded_id 등', verbose_name='광고 유닛 ID')),
                ('priority', models.IntegerField(default=0, help_text='숫자가 높을수록 우선순위 높음', verbose_name='우선순위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '광고 설정',
                'verbose_name_plural': '광고 설정',
                'db_table': 'ad_configs',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_enabled'], name='idx_adcfg_platform_enabled'), models.Index(fields=['-priority'], name='idx_adcfg_priority')],
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='설정 키')),
                ('value', models.JSONField(help_text='JSON 형식으로 저장', verbose_name='설정 값')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '앱 설정',
                'verbose_name_plural': '앱 설정',
                'db_table': 'app_settings',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='idx_appsetting_key'), models.Index(fields=['is_active'], name='idx_appsetting_active')],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='플랫폼')),
                ('version', models.CharField(help_text='예: 1.3.5', max_length=20, verbose_name='버전')),
                ('build_number', models.IntegerField(help_text='예: 50', verbose_name='빌드 번호')),
                ('minimum_version', models.CharField(help_text='이 버전보다 낮으면 강제 업데이트 필요', max_length=20, verbose_name='최소 지원 버전')),
                ('force_update', models.BooleanField(default=False, verbose_name='강제 업데이트 여부')),
                ('update_message', models.TextField(blank=True, null=True, verbose_name='업데이트 메시지')),
                ('store_url', models.URLField(help_text='Play Store 또는 App Store URL', max_length=500, verbose_name='스토어 URL')),
                ('is_active', models.BooleanField(default=True, help_text='가장 최신 활성 버전이 사용됨', verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '앱 버전',
                'verbose_name_plural': '앱 버전',
                'db_table': 'app_versions',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='idx_appver_platform_active'), models.Index(fields=['-created_at'], name='idx_appver_created')],
            },
        ),
    ]
