# Generated by Django 5.2.8 on 2025-11-27 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='예: /api/v1/campaigns/*, /api/v1/auth/*, 또는 * (전체)', max_length=200, unique=True, verbose_name='엔드포인트')),
                ('max_requests', models.IntegerField(help_text='시간 윈도우 내 최대 허용 요청 수', validators=[django.core.validators.MinValueValidator(1)], verbose_name='최대 요청 수')),
                ('window_seconds', models.IntegerField(help_text='Rate limit을 체크할 시간 범위 (예: 60초)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='시간 윈도우 (초)')),
                ('apply_to_authenticated', models.BooleanField(default=True, help_text='로그인한 사용자에게도 Rate Limit 적용', verbose_name='인증된 사용자에게 적용')),
                ('apply_to_anonymous', models.BooleanField(default=True, help_text='비로그인 사용자에게 Rate Limit 적용', verbose_name='익명 사용자에게 적용')),
                ('block_duration_seconds', models.IntegerField(default=300, help_text='Rate Limit 초과 시 차단할 시간 (0=차단 없음)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='차단 시간 (초)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('priority', models.IntegerField(default=0, help_text='숫자가 높을수록 먼저 적용됨 (특정 엔드포인트를 * 보다 먼저 체크)', verbose_name='우선순위')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'Rate Limit 설정',
                'verbose_name_plural': 'Rate Limit 설정',
                'db_table': 'rate_limit_configs',
                'ordering': ['-priority', 'endpoint'],
                'indexes': [models.Index(fields=['endpoint', 'is_enabled'], name='idx_ratelimit_endpoint'), models.Index(fields=['-priority'], name='idx_ratelimit_priority')],
            },
        ),
    ]
