# Generated by Django 5.2.8 on 2025-11-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_optimize_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시간', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시간', verbose_name='수정일시')),
                ('keyword', models.CharField(help_text='알람을 받을 키워드', max_length=100, verbose_name='키워드')),
                ('anonymous_session_id', models.CharField(blank=True, help_text='익명 사용자의 세션 ID', max_length=255, null=True, verbose_name='익명 세션 ID')),
                ('is_active', models.BooleanField(default=True, help_text='알람 활성화 여부', verbose_name='활성 상태')),
                ('user', models.ForeignKey(blank=True, help_text='키워드를 등록한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '관심 키워드',
                'verbose_name_plural': '관심 키워드',
                'db_table': 'keyword_alerts_keywords',
            },
        ),
        migrations.CreateModel(
            name='KeywordAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시간', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시간', verbose_name='수정일시')),
                ('matched_field', models.CharField(help_text='키워드가 매칭된 필드 (title, description 등)', max_length=50, verbose_name='매칭 필드')),
                ('is_read', models.BooleanField(default=False, help_text='사용자가 알람을 확인했는지 여부', verbose_name='읽음 여부')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_alerts', to='campaigns.campaign', verbose_name='캠페인')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='keyword_alerts.keyword', verbose_name='키워드')),
            ],
            options={
                'verbose_name': '키워드 알람',
                'verbose_name_plural': '키워드 알람',
                'db_table': 'keyword_alerts_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['user', 'is_active'], name='keyword_ale_user_id_e18c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['anonymous_session_id', 'is_active'], name='keyword_ale_anonymo_2936ec_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['keyword'], name='keyword_ale_keyword_5c7b32_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('anonymous_session_id__isnull', False), _connector='OR'), name='keyword_has_owner'),
        ),
        migrations.AddIndex(
            model_name='keywordalert',
            index=models.Index(fields=['keyword', 'is_read'], name='keyword_ale_keyword_3d44d6_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordalert',
            index=models.Index(fields=['campaign'], name='keyword_ale_campaig_2f61a0_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordalert',
            index=models.Index(fields=['-created_at'], name='keyword_ale_created_704aa6_idx'),
        ),
    ]
