# Generated by Django 5.2.8 on 2025-11-25
# FCM 디바이스 토큰 저장 모델 추가

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시간', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시간', verbose_name='수정일시')),
                ('fcm_token', models.CharField(help_text='Firebase Cloud Messaging 디바이스 토큰', max_length=500, unique=True, verbose_name='FCM 토큰')),
                ('anonymous_session_id', models.CharField(blank=True, help_text='익명 사용자의 세션 ID', max_length=255, null=True, verbose_name='익명 세션 ID')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='디바이스 타입')),
                ('is_active', models.BooleanField(default=True, help_text='푸시 수신 활성화 여부', verbose_name='활성 상태')),
                ('user', models.ForeignKey(blank=True, help_text='토큰을 등록한 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'FCM 디바이스',
                'verbose_name_plural': 'FCM 디바이스',
                'db_table': 'keyword_alerts_fcm_devices',
            },
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['user', 'is_active'], name='keyword_ale_user_id_fcm_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['anonymous_session_id', 'is_active'], name='keyword_ale_anon_fcm_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmdevice',
            index=models.Index(fields=['fcm_token'], name='keyword_ale_token_idx'),
        ),
        migrations.AddConstraint(
            model_name='fcmdevice',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('anonymous_session_id__isnull', False), _connector='OR'), name='fcm_device_has_owner'),
        ),
    ]
