# Generated by Django 5.2.8 on 2025-11-26 15:56
# Modified: 인덱스 이름 변경 제거 (불필요하고 마이그레이션 오류 발생)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_optimize_database_indexes'),
        ('keyword_alerts', '0002_add_fcm_device'),
    ]

    operations = [
        # 캠페인 삭제 시 알림 히스토리 보존을 위해 SET_NULL로 변경
        migrations.AlterField(
            model_name='keywordalert',
            name='campaign',
            field=models.ForeignKey(
                blank=True,
                help_text='캠페인이 삭제되어도 알림 히스토리는 보존됨',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='keyword_alerts',
                to='campaigns.campaign',
                verbose_name='캠페인'
            ),
        ),
    ]
