# Generated by Django 5.2.8 on 2025-11-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_optimize_database_indexes'),
        ('keyword_alerts', '0002_add_fcm_device'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_user_id_23d013_idx',
            old_name='keyword_ale_user_id_fcm_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_anonymo_9d4075_idx',
            old_name='keyword_ale_anon_fcm_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_fcm_tok_fd1b59_idx',
            old_name='keyword_ale_token_idx',
        ),
        migrations.AlterField(
            model_name='keywordalert',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='캠페인이 삭제되어도 알림 히스토리는 보존됨', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_alerts', to='campaigns.campaign', verbose_name='캠페인'),
        ),
    ]
