# Generated by Django 5.2.8 on 2025-11-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_alerts', '0003_campaign_set_null'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_user_id_23d013_idx',
            old_name='keyword_ale_user_id_fcm_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_anonymo_9d4075_idx',
            old_name='keyword_ale_anon_fcm_idx',
        ),
        migrations.RenameIndex(
            model_name='fcmdevice',
            new_name='keyword_ale_fcm_tok_fd1b59_idx',
            old_name='keyword_ale_token_idx',
        ),
    ]
