# Generated by Django 5.2.8 on 2025-11-27 08:40

from django.db import migrations


class Migration(migrations.Migration):
    """
    FCMDevice 모델의 인덱스 이름 변경을 시도하는 마이그레이션
    
    프로덕션 환경에서 기존 인덱스 이름이 존재하지 않아 오류 발생
    안전을 위해 no-op(빈 작업) 마이그레이션으로 변경
    인덱스 이름 변경은 기능에 영향을 주지 않음
    """

    dependencies = [
        ('keyword_alerts', '0003_campaign_set_null'),
    ]

    operations = [
        # 인덱스 이름 변경이 프로덕션에서 오류를 발생시켜 제거
        # 기존 인덱스는 정상 작동하며, 이름 변경은 기능에 영향 없음
    ]
