# Generated by Django 5.2.8 on 2025-11-27 08:43

from django.db import migrations


def rename_indexes_if_exists(apps, schema_editor):
    """
    인덱스가 존재하는 경우에만 이름 변경
    존재하지 않으면 스킵 (오류 방지)
    """
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # 인덱스 이름 매핑 (old_name -> new_name)
        index_renames = [
            ('keyword_ale_user_id_fcm_idx', 'fcm_user_active_idx'),
            ('keyword_ale_anon_fcm_idx', 'fcm_anon_active_idx'),
            ('keyword_ale_token_idx', 'fcm_token_idx'),
            # Django가 자동 생성한 해시 이름도 처리
            ('keyword_ale_user_id_23d013_idx', 'fcm_user_active_idx'),
            ('keyword_ale_anonymo_9d4075_idx', 'fcm_anon_active_idx'),
            ('keyword_ale_fcm_tok_fd1b59_idx', 'fcm_token_idx'),
        ]
        
        for old_name, new_name in index_renames:
            # 인덱스 존재 여부 확인
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE schemaname = 'public' 
                AND indexname = %s
            """, [old_name])
            
            if cursor.fetchone():
                try:
                    cursor.execute(f"ALTER INDEX {old_name} RENAME TO {new_name}")
                    print(f"✓ 인덱스 이름 변경: {old_name} -> {new_name}")
                except Exception as e:
                    # 이미 새 이름의 인덱스가 존재하는 경우 스킵
                    print(f"⚠ 인덱스 이름 변경 스킵: {old_name} (이미 {new_name}이 존재하거나 오류 발생)")
            else:
                print(f"ℹ 인덱스 없음 (스킵): {old_name}")


def reverse_rename_indexes(apps, schema_editor):
    """역방향 마이그레이션 (필요시)"""
    pass


class Migration(migrations.Migration):
    """
    FCMDevice 모델의 인덱스 이름을 명시적 이름으로 변경
    
    안전성을 위해 조건부로 처리:
    - 기존 인덱스가 존재하는 경우에만 rename
    - 존재하지 않으면 스킵 (오류 방지)
    """

    dependencies = [
        ('keyword_alerts', '0004_rename_keyword_ale_user_id_fcm_idx_keyword_ale_user_id_23d013_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            rename_indexes_if_exists,
            reverse_rename_indexes,
        ),
    ]
